### ISSUE TITLE
Copy and Cut is performing slow

### ISSUE THREAD

**Issue by Morgy93** [SrTobi/code-clip-ring#2]
While having the extension installed `ctrl+x` (cut) and `ctrl+c` (copy) is pretty slow and takes like 1-2 seconds to perform.
This actually causes another funny problem:
If you copy some stuff and don't wait for like two seconds, then the clipboard is just empty and `ctrl+v` (paste) just pastes some empty string or still uses the previous item.

**Comment by SrTobi** [comment]
Wich OS Do you use?

**Comment by Morgy93** [comment]
@SrTobi Windows 10 Pro

**Comment by SrTobi** [comment]
@Morgy93 Hmm yea... the problem is the module i am using to access the clipboard, which does some weird stuff to copy and paste to the clipboard... to paste, it actually starts a vba script which then starts a windows program which then prints the clipboard content to stdout... then the script redirects this to the extension which then does some weird encoding.... that takes time...

if you know a better module to access the clipboard feel free to contribute :smile: 

another possibility would be to ask the devs of vscode to expose an clipboard api
